### ISSUE TITLE
Add a theme function so link output can be overridden

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/socialfield#16]
We identified in https://github.com/backdrop-contrib/socialfield/issues/13 that there was no way to override the output of a sociallink in the theme. This will be a problem for many other use-cases as well and should be addressed.

**Comment by jenlampton** [comment]
I've created a PR at https://github.com/backdrop-contrib/socialfield/pull/17 that will allow variations on theme_link for the socialfield links. `theme_link__socialfield`  will work on all socialfield links, and `theme_link__socialfield__[service]` will work for a service-specific override (for example, facebook only).

**Comment by CybersecDan** [comment]
Cool. Thanks for the PR Jen. Would you like me to complete the merge? Also, will this make it so we can override "nofollow" via theme-override instead?

**Comment by jenlampton** [comment]
> Would you like me to complete the merge?

It could use some testing. If it looks good to you too, then yes merge away. :)  And yes, this will allow all the output to be overridden, including both adding (or removing) the nofollow links.

**Comment by CybersecDan** [comment]
Awesome. I'll do some testing as well then. :)

**Comment by CybersecDan** [comment]
Tested and confirmed it works. Thanks for the help and the PR @jenlampton. :)
