### ISSUE TITLE
Add fall-back icons from Icon API incase no service is being used. 

### ISSUE THREAD

**Issue by auxiliaryjoel** [backdrop-contrib/socialfield#18]
The display of the content seems to cut off the majority of the area, only showing a small portion of the background area, not sure how to fix this?

**Comment by stpaultim** [comment]
I'm seeing the same problem. The background color is loading, but not the icon. I've not had time to try and debug the cause of this problem.

**Comment by laryn** [comment]
I think this module relies on an icon service to provide the fonts (or manually added in your theme):

> The classes can be used in conjunction with icon fonts (such as fontello or font awesome) to display the links as icons.

**Comment by jenlampton** [comment]
Added in `2d96442` 🎉

**Comment by jenlampton** [comment]
I've done a rework to better support IconAPI Icons in the 2.x branch. 
Ig you are interested, please test https://github.com/backdrop-contrib/socialfield/releases/tag/1.x-2.0.0-alpha and provide feedback.
